/*
 * PanelCrear2.java
 *
 * Created on January 14, 2001, 1:40 AM
 */
 
package tuplas;
import javax.swing.*;
import java.util.*;
/** 
 *
 * @author  root_vaio
 * @version 
 */
public class PanelCrear extends javax.swing.JPanel {

  /** La clase contenedora de este Panel */
  private TuplaAdmin _contenedor;
  
  /** Lista de servidores */
  private Vector _listaServidores;
  
  /** Creates new form PanelCrear2 */
  public PanelCrear(TuplaAdmin c) {
    this._contenedor = c;
    initComponents ();
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the FormEditor.
   */
  private void initComponents () {//GEN-BEGIN:initComponents
    jLabel1 = new javax.swing.JLabel ();
    jLabel2 = new javax.swing.JLabel ();
    jTextFieldNombreTupla = new javax.swing.JTextField ();
    jTextFieldDimension = new javax.swing.JTextField ();
    jLabel3 = new javax.swing.JLabel ();
    jComboBoxTipo = new javax.swing.JComboBox ();
    jPanel1 = new javax.swing.JPanel ();
    jLabel4 = new javax.swing.JLabel ();
    jTextFieldNombreServidor = new javax.swing.JTextField ();
    jComboBoxServidores = new javax.swing.JComboBox ();
    jPanel2 = new javax.swing.JPanel ();
    jButtonAgregar = new javax.swing.JButton ();
    jButtonEliminar = new javax.swing.JButton ();
    jButtonCrear = new javax.swing.JButton ();
    setLayout (new java.awt.GridBagLayout ());
    java.awt.GridBagConstraints gridBagConstraints1;

    jLabel1.setText ("Tipo");


    gridBagConstraints1 = new java.awt.GridBagConstraints ();
    gridBagConstraints1.gridx = 0;
    gridBagConstraints1.gridy = 2;
    gridBagConstraints1.anchor = java.awt.GridBagConstraints.WEST;
    add (jLabel1, gridBagConstraints1);

    jLabel2.setText ("Nombre");


    gridBagConstraints1 = new java.awt.GridBagConstraints ();
    gridBagConstraints1.anchor = java.awt.GridBagConstraints.WEST;
    add (jLabel2, gridBagConstraints1);

    jTextFieldNombreTupla.setPreferredSize (new java.awt.Dimension(150, 20));
    jTextFieldNombreTupla.setMaximumSize (new java.awt.Dimension(150, 20));
    jTextFieldNombreTupla.setMinimumSize (new java.awt.Dimension(150, 20));


    gridBagConstraints1 = new java.awt.GridBagConstraints ();
    gridBagConstraints1.insets = new java.awt.Insets (0, 8, 4, 0);
    gridBagConstraints1.anchor = java.awt.GridBagConstraints.WEST;
    add (jTextFieldNombreTupla, gridBagConstraints1);

    jTextFieldDimension.setPreferredSize (new java.awt.Dimension(50, 20));
    jTextFieldDimension.setMaximumSize (new java.awt.Dimension(50, 20));
    jTextFieldDimension.setMinimumSize (new java.awt.Dimension(50, 20));


    gridBagConstraints1 = new java.awt.GridBagConstraints ();
    gridBagConstraints1.gridx = 1;
    gridBagConstraints1.gridy = 1;
    gridBagConstraints1.insets = new java.awt.Insets (0, 8, 4, 0);
    gridBagConstraints1.anchor = java.awt.GridBagConstraints.WEST;
    add (jTextFieldDimension, gridBagConstraints1);

    jLabel3.setText ("Dimensión");


    gridBagConstraints1 = new java.awt.GridBagConstraints ();
    gridBagConstraints1.gridx = 0;
    gridBagConstraints1.gridy = 1;
    gridBagConstraints1.anchor = java.awt.GridBagConstraints.WEST;
    add (jLabel3, gridBagConstraints1);

    jComboBoxTipo.setBorder (new javax.swing.border.SoftBevelBorder(0));
    jComboBoxTipo.setMinimumSize (new java.awt.Dimension(130, 25));
    jComboBoxTipo.setBackground (java.awt.Color.white);
    jComboBoxTipo.setMaximumSize (new java.awt.Dimension(130, 25));
    jComboBoxTipo.addItem(new String("Replicado"));
    jComboBoxTipo.addItem(new String("Segmentado"));
    jComboBoxTipo.addItem(new String("Particionado"));


    gridBagConstraints1 = new java.awt.GridBagConstraints ();
    gridBagConstraints1.gridx = 1;
    gridBagConstraints1.gridy = 2;
    gridBagConstraints1.insets = new java.awt.Insets (0, 8, 0, 0);
    gridBagConstraints1.anchor = java.awt.GridBagConstraints.WEST;
    add (jComboBoxTipo, gridBagConstraints1);

    jPanel1.setLayout (new java.awt.GridBagLayout ());
    java.awt.GridBagConstraints gridBagConstraints2;
    jPanel1.setBorder (new javax.swing.border.TitledBorder(
    new javax.swing.border.EtchedBorder(), "Lista de Servidores"));

      jLabel4.setText ("Nombre del Servidor");
  
      gridBagConstraints2 = new java.awt.GridBagConstraints ();
      gridBagConstraints2.insets = new java.awt.Insets (0, 0, 2, 0);
      jPanel1.add (jLabel4, gridBagConstraints2);
  
      jTextFieldNombreServidor.setPreferredSize (new java.awt.Dimension(150, 20));
      jTextFieldNombreServidor.setMaximumSize (new java.awt.Dimension(150, 20));
      jTextFieldNombreServidor.setMinimumSize (new java.awt.Dimension(150, 20));
  
      gridBagConstraints2 = new java.awt.GridBagConstraints ();
      gridBagConstraints2.insets = new java.awt.Insets (0, 4, 2, 0);
      jPanel1.add (jTextFieldNombreServidor, gridBagConstraints2);
  
  
      gridBagConstraints2 = new java.awt.GridBagConstraints ();
      gridBagConstraints2.gridx = 0;
      gridBagConstraints2.gridy = 1;
      jPanel1.add (jComboBoxServidores, gridBagConstraints2);
  
      jPanel2.setLayout (new java.awt.GridBagLayout ());
      java.awt.GridBagConstraints gridBagConstraints3;
  
        jButtonAgregar.setText ("Agregar Servidor");
        jButtonAgregar.addActionListener (new java.awt.event.ActionListener () {
          public void actionPerformed (java.awt.event.ActionEvent evt) {
            jButtonAgregarActionPerformed (evt);
          }
        }
        );
    
        gridBagConstraints3 = new java.awt.GridBagConstraints ();
        gridBagConstraints3.gridx = 0;
        gridBagConstraints3.gridy = 0;
        gridBagConstraints3.insets = new java.awt.Insets (0, 4, 0, 0);
        jPanel2.add (jButtonAgregar, gridBagConstraints3);
    
        jButtonEliminar.setText ("Eliminar Servidor");
        jButtonEliminar.addActionListener (new java.awt.event.ActionListener () {
          public void actionPerformed (java.awt.event.ActionEvent evt) {
            jButtonEliminarActionPerformed (evt);
          }
        }
        );
    
        gridBagConstraints3 = new java.awt.GridBagConstraints ();
        gridBagConstraints3.gridx = 0;
        gridBagConstraints3.gridy = 1;
        gridBagConstraints3.insets = new java.awt.Insets (0, 4, 0, 0);
        jPanel2.add (jButtonEliminar, gridBagConstraints3);
    
      gridBagConstraints2 = new java.awt.GridBagConstraints ();
      gridBagConstraints2.gridx = 1;
      gridBagConstraints2.gridy = 1;
      gridBagConstraints2.insets = new java.awt.Insets (2, 2, 2, 2);
      gridBagConstraints2.anchor = java.awt.GridBagConstraints.NORTHWEST;
      jPanel1.add (jPanel2, gridBagConstraints2);
  

    gridBagConstraints1 = new java.awt.GridBagConstraints ();
    gridBagConstraints1.gridx = 0;
    gridBagConstraints1.gridy = 3;
    gridBagConstraints1.gridwidth = 2;
    add (jPanel1, gridBagConstraints1);

    jButtonCrear.setText ("Crear");
    jButtonCrear.addActionListener (new java.awt.event.ActionListener () {
      public void actionPerformed (java.awt.event.ActionEvent evt) {
        jButtonCrearActionPerformed (evt);
      }
    }
    );


    gridBagConstraints1 = new java.awt.GridBagConstraints ();
    gridBagConstraints1.gridx = 0;
    gridBagConstraints1.gridy = 5;
    gridBagConstraints1.gridwidth = 2;
    gridBagConstraints1.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints1.insets = new java.awt.Insets (4, 4, 4, 4);
    add (jButtonCrear, gridBagConstraints1);

  }//GEN-END:initComponents

  /** Boton para Crear una Tupla */
  private void jButtonCrearActionPerformed (java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearActionPerformed
  
    //Tomar todos los parametros.
    String nombre = jTextFieldNombreTupla.getText();
    
    int dimension = 0;
    try
    {
      dimension = Integer.parseInt(jTextFieldDimension.getText());
    }
    catch (Exception a)
    {
      jTextFieldDimension.setText("1");
      dimension = 1;
    };
    
    int tipo = jComboBoxTipo.getSelectedIndex();
    
    String[] lista = new String[jComboBoxServidores.getItemCount()];
    
    //Tomar la lista de Servidores.
    for (int i=0; i < jComboBoxServidores.getItemCount(); i++)
      lista[i] = new String((String) jComboBoxServidores.getItemAt(i));
    
    
    if ( (nombre.length() == 0) || (dimension < 1) || (jComboBoxServidores.getItemCount() == 0))
      JOptionPane.showMessageDialog(null,new String("Verifique los datos e intente de nuevo"),new String("TuplaAdmin :: Advertencia"),JOptionPane.WARNING_MESSAGE);
    else
    {
      boolean sirvio = true;
      //Mandar a ejecutar, si fueron especificados todos.
      try
      {
        _contenedor._objetoRemoto.crear(nombre,dimension,tipo,lista);
      }
      catch (Exception e)
      {
        sirvio = false;
        JOptionPane.showMessageDialog(null,new String("No se pudo ejecutar el metodo Crear"),new String("TuplaAdmin :: Error"),JOptionPane.ERROR_MESSAGE);
      };
      
      if (sirvio)
      {
        //Limpiar todo.
        jTextFieldDimension.setText("");
        jTextFieldNombreServidor.setText("");
        jTextFieldNombreTupla.setText("");
        jComboBoxServidores.removeAllItems();
        jButtonEliminar.setEnabled(false);
      }
    }
    
    
  }//GEN-LAST:event_jButtonCrearActionPerformed

  /** Boton Eliminar Servidor */
  private void jButtonEliminarActionPerformed (java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
    if (jComboBoxServidores.getItemCount() == 0)
    {
       JOptionPane.showMessageDialog(null,new String("Verifique los datos e intente de nuevo"),"TuplaAdmin :: Advertencia",JOptionPane.WARNING_MESSAGE);
       jButtonEliminar.setEnabled(false);
    }
    else
    {
      jComboBoxServidores.removeItemAt(jComboBoxServidores.getSelectedIndex());
      if (jComboBoxServidores.getItemCount() == 0)
        jButtonEliminar.setEnabled(false);
    }
  }//GEN-LAST:event_jButtonEliminarActionPerformed

  /** Boton para agregar servidor */
  private void jButtonAgregarActionPerformed (java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarActionPerformed

    String nombre = jTextFieldNombreServidor.getText();
    
    if (nombre.length() > 0)
    {
      jComboBoxServidores.addItem(nombre);
        if (jComboBoxServidores.getItemCount() > 0)
          jButtonEliminar.setEnabled(true);
      jTextFieldNombreServidor.setText("");
    }
  }//GEN-LAST:event_jButtonAgregarActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JTextField jTextFieldNombreTupla;
  private javax.swing.JTextField jTextFieldDimension;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JComboBox jComboBoxTipo;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JTextField jTextFieldNombreServidor;
  private javax.swing.JComboBox jComboBoxServidores;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JButton jButtonAgregar;
  private javax.swing.JButton jButtonEliminar;
  private javax.swing.JButton jButtonCrear;
  // End of variables declaration//GEN-END:variables

}