/*
 * PanelComun.java
 *
 * Created on January 12, 2001, 2:36 AM
 */
 
package tuplas;
import javax.swing.*;
/** 
 *
 * @author  Valued Sony Customer
 * @version 
 */
public class PanelComun extends javax.swing.JPanel {

  private TuplaAdmin _contenedor;
  
  /** Creates new form PanelComun */
  public PanelComun(TuplaAdmin c) {
    initComponents ();
    _contenedor = c;
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the FormEditor.
   */
  private void initComponents () {//GEN-BEGIN:initComponents
    jPanelEliminar = new javax.swing.JPanel ();
    jLabel1 = new javax.swing.JLabel ();
    jTextFieldNombreEliminacion = new javax.swing.JTextField ();
    jButtonEliminar = new javax.swing.JButton ();
    jPanelInsertar = new javax.swing.JPanel ();
    jLabel2 = new javax.swing.JLabel ();
    jTextFieldNombreInsertado = new javax.swing.JTextField ();
    jLabel3 = new javax.swing.JLabel ();
    jTextFieldTi = new javax.swing.JTextField ();
    jButtonInsertar = new javax.swing.JButton ();
    jPanelBorrar = new javax.swing.JPanel ();
    jLabel4 = new javax.swing.JLabel ();
    jTextFieldNombreBorrado = new javax.swing.JTextField ();
    jLabel5 = new javax.swing.JLabel ();
    jTextFieldClaveBorrado = new javax.swing.JTextField ();
    jButtonBorrar = new javax.swing.JButton ();
    jPanelBuscar = new javax.swing.JPanel ();
    jLabel6 = new javax.swing.JLabel ();
    jTextFieldNombreBusqueda = new javax.swing.JTextField ();
    jLabel7 = new javax.swing.JLabel ();
    jTextFieldClaveBusqueda = new javax.swing.JTextField ();
    jButtonBuscar = new javax.swing.JButton ();
    jListBusqueda = new javax.swing.JList ();
    jPanelConfiguracion = new javax.swing.JPanel ();
    jLabel8 = new javax.swing.JLabel ();
    jTextFieldNombreConfiguracion = new javax.swing.JTextField ();
    jButtonConfiguracion = new javax.swing.JButton ();
    jLabelResultadoConfiguracion = new javax.swing.JLabel ();
    jPanelActualizar = new javax.swing.JPanel ();
    jLabel9 = new javax.swing.JLabel ();
    jTextFieldNombreActualizar = new javax.swing.JTextField ();
    jLabel10 = new javax.swing.JLabel ();
    jTextFieldClaveActualizar = new javax.swing.JTextField ();
    jLabel11 = new javax.swing.JLabel ();
    jTextFieldPosicionActualizar = new javax.swing.JTextField ();
    jLabel12 = new javax.swing.JLabel ();
    jTextFieldValorActualizar = new javax.swing.JTextField ();
    jButtonActualizar = new javax.swing.JButton ();
    setLayout (new java.awt.GridBagLayout ());
    java.awt.GridBagConstraints gridBagConstraints1;

    jPanelEliminar.setLayout (new java.awt.GridBagLayout ());
    java.awt.GridBagConstraints gridBagConstraints2;
    jPanelEliminar.setBorder (new javax.swing.border.TitledBorder("Eliminación"));

      jLabel1.setText ("Nombre");
  
      gridBagConstraints2 = new java.awt.GridBagConstraints ();
      jPanelEliminar.add (jLabel1, gridBagConstraints2);
  
      jTextFieldNombreEliminacion.setPreferredSize (new java.awt.Dimension(150, 20));
      jTextFieldNombreEliminacion.setMaximumSize (new java.awt.Dimension(150, 20));
      jTextFieldNombreEliminacion.setMinimumSize (new java.awt.Dimension(150, 20));
  
      gridBagConstraints2 = new java.awt.GridBagConstraints ();
      gridBagConstraints2.insets = new java.awt.Insets (2, 3, 2, 2);
      jPanelEliminar.add (jTextFieldNombreEliminacion, gridBagConstraints2);
  
      jButtonEliminar.setText ("Eliminar");
      jButtonEliminar.addActionListener (new java.awt.event.ActionListener () {
        public void actionPerformed (java.awt.event.ActionEvent evt) {
          jButtonEliminarActionPerformed (evt);
        }
      }
      );
  
      gridBagConstraints2 = new java.awt.GridBagConstraints ();
      gridBagConstraints2.gridx = 0;
      gridBagConstraints2.gridy = 1;
      gridBagConstraints2.gridwidth = 2;
      gridBagConstraints2.fill = java.awt.GridBagConstraints.HORIZONTAL;
      gridBagConstraints2.insets = new java.awt.Insets (4, 4, 4, 4);
      jPanelEliminar.add (jButtonEliminar, gridBagConstraints2);
  

    gridBagConstraints1 = new java.awt.GridBagConstraints ();
    gridBagConstraints1.fill = java.awt.GridBagConstraints.BOTH;
    add (jPanelEliminar, gridBagConstraints1);

    jPanelInsertar.setLayout (new java.awt.GridBagLayout ());
    java.awt.GridBagConstraints gridBagConstraints3;
    jPanelInsertar.setBorder (new javax.swing.border.TitledBorder("Insertado"));

      jLabel2.setText ("Nombre");
  
      gridBagConstraints3 = new java.awt.GridBagConstraints ();
      jPanelInsertar.add (jLabel2, gridBagConstraints3);
  
      jTextFieldNombreInsertado.setPreferredSize (new java.awt.Dimension(150, 20));
      jTextFieldNombreInsertado.setMaximumSize (new java.awt.Dimension(150, 20));
      jTextFieldNombreInsertado.setMinimumSize (new java.awt.Dimension(150, 20));
  
      gridBagConstraints3 = new java.awt.GridBagConstraints ();
      gridBagConstraints3.insets = new java.awt.Insets (4, 4, 4, 4);
      jPanelInsertar.add (jTextFieldNombreInsertado, gridBagConstraints3);
  
      jLabel3.setText ("ti");
  
      gridBagConstraints3 = new java.awt.GridBagConstraints ();
      gridBagConstraints3.gridx = 0;
      gridBagConstraints3.gridy = 1;
      jPanelInsertar.add (jLabel3, gridBagConstraints3);
  
      jTextFieldTi.setPreferredSize (new java.awt.Dimension(150, 20));
      jTextFieldTi.setMaximumSize (new java.awt.Dimension(150, 20));
      jTextFieldTi.setMinimumSize (new java.awt.Dimension(150, 20));
  
      gridBagConstraints3 = new java.awt.GridBagConstraints ();
      gridBagConstraints3.gridx = 1;
      gridBagConstraints3.gridy = 1;
      gridBagConstraints3.insets = new java.awt.Insets (0, 4, 4, 4);
      jPanelInsertar.add (jTextFieldTi, gridBagConstraints3);
  
      jButtonInsertar.setText ("Insertar");
      jButtonInsertar.addActionListener (new java.awt.event.ActionListener () {
        public void actionPerformed (java.awt.event.ActionEvent evt) {
          jButtonInsertarActionPerformed (evt);
        }
      }
      );
  
      gridBagConstraints3 = new java.awt.GridBagConstraints ();
      gridBagConstraints3.gridx = 0;
      gridBagConstraints3.gridy = 2;
      gridBagConstraints3.gridwidth = 2;
      gridBagConstraints3.fill = java.awt.GridBagConstraints.HORIZONTAL;
      gridBagConstraints3.insets = new java.awt.Insets (4, 4, 4, 4);
      jPanelInsertar.add (jButtonInsertar, gridBagConstraints3);
  

    gridBagConstraints1 = new java.awt.GridBagConstraints ();
    gridBagConstraints1.gridx = 1;
    gridBagConstraints1.gridy = 0;
    gridBagConstraints1.fill = java.awt.GridBagConstraints.HORIZONTAL;
    add (jPanelInsertar, gridBagConstraints1);

    jPanelBorrar.setLayout (new java.awt.GridBagLayout ());
    java.awt.GridBagConstraints gridBagConstraints4;
    jPanelBorrar.setBorder (new javax.swing.border.TitledBorder("Borrado"));

      jLabel4.setText ("Nombre");
  
      gridBagConstraints4 = new java.awt.GridBagConstraints ();
      jPanelBorrar.add (jLabel4, gridBagConstraints4);
  
      jTextFieldNombreBorrado.setPreferredSize (new java.awt.Dimension(150, 20));
      jTextFieldNombreBorrado.setMaximumSize (new java.awt.Dimension(150, 20));
      jTextFieldNombreBorrado.setMinimumSize (new java.awt.Dimension(150, 20));
  
      gridBagConstraints4 = new java.awt.GridBagConstraints ();
      gridBagConstraints4.insets = new java.awt.Insets (0, 4, 0, 4);
      jPanelBorrar.add (jTextFieldNombreBorrado, gridBagConstraints4);
  
      jLabel5.setText ("Clave");
  
      gridBagConstraints4 = new java.awt.GridBagConstraints ();
      gridBagConstraints4.gridx = 0;
      gridBagConstraints4.gridy = 1;
      jPanelBorrar.add (jLabel5, gridBagConstraints4);
  
      jTextFieldClaveBorrado.setPreferredSize (new java.awt.Dimension(150, 20));
      jTextFieldClaveBorrado.setMaximumSize (new java.awt.Dimension(150, 20));
      jTextFieldClaveBorrado.setMinimumSize (new java.awt.Dimension(150, 20));
  
      gridBagConstraints4 = new java.awt.GridBagConstraints ();
      gridBagConstraints4.gridx = 1;
      gridBagConstraints4.gridy = 1;
      gridBagConstraints4.insets = new java.awt.Insets (0, 4, 0, 4);
      jPanelBorrar.add (jTextFieldClaveBorrado, gridBagConstraints4);
  
      jButtonBorrar.setText ("Borrar");
      jButtonBorrar.addActionListener (new java.awt.event.ActionListener () {
        public void actionPerformed (java.awt.event.ActionEvent evt) {
          jButtonBorrarActionPerformed (evt);
        }
      }
      );
  
      gridBagConstraints4 = new java.awt.GridBagConstraints ();
      gridBagConstraints4.gridx = 0;
      gridBagConstraints4.gridy = 2;
      gridBagConstraints4.gridwidth = 2;
      gridBagConstraints4.fill = java.awt.GridBagConstraints.HORIZONTAL;
      gridBagConstraints4.insets = new java.awt.Insets (4, 4, 4, 4);
      jPanelBorrar.add (jButtonBorrar, gridBagConstraints4);
  

    gridBagConstraints1 = new java.awt.GridBagConstraints ();
    gridBagConstraints1.gridx = 0;
    gridBagConstraints1.gridy = 1;
    gridBagConstraints1.fill = java.awt.GridBagConstraints.BOTH;
    add (jPanelBorrar, gridBagConstraints1);

    jPanelBuscar.setLayout (new java.awt.GridBagLayout ());
    java.awt.GridBagConstraints gridBagConstraints5;
    jPanelBuscar.setBorder (new javax.swing.border.TitledBorder("Busqueda"));

      jLabel6.setText ("Nombre");
  
      gridBagConstraints5 = new java.awt.GridBagConstraints ();
      jPanelBuscar.add (jLabel6, gridBagConstraints5);
  
      jTextFieldNombreBusqueda.setPreferredSize (new java.awt.Dimension(150, 20));
      jTextFieldNombreBusqueda.setMaximumSize (new java.awt.Dimension(150, 20));
      jTextFieldNombreBusqueda.setMinimumSize (new java.awt.Dimension(150, 20));
  
      gridBagConstraints5 = new java.awt.GridBagConstraints ();
      gridBagConstraints5.insets = new java.awt.Insets (4, 4, 4, 4);
      jPanelBuscar.add (jTextFieldNombreBusqueda, gridBagConstraints5);
  
      jLabel7.setText ("Clave");
  
      gridBagConstraints5 = new java.awt.GridBagConstraints ();
      gridBagConstraints5.gridx = 0;
      gridBagConstraints5.gridy = 1;
      jPanelBuscar.add (jLabel7, gridBagConstraints5);
  
      jTextFieldClaveBusqueda.setPreferredSize (new java.awt.Dimension(150, 20));
      jTextFieldClaveBusqueda.setMaximumSize (new java.awt.Dimension(150, 20));
      jTextFieldClaveBusqueda.setMinimumSize (new java.awt.Dimension(150, 20));
  
      gridBagConstraints5 = new java.awt.GridBagConstraints ();
      gridBagConstraints5.gridx = 1;
      gridBagConstraints5.gridy = 1;
      gridBagConstraints5.insets = new java.awt.Insets (0, 4, 4, 4);
      jPanelBuscar.add (jTextFieldClaveBusqueda, gridBagConstraints5);
  
      jButtonBuscar.setText ("Buscar");
      jButtonBuscar.addActionListener (new java.awt.event.ActionListener () {
        public void actionPerformed (java.awt.event.ActionEvent evt) {
          jButtonBuscarActionPerformed (evt);
        }
      }
      );
  
      gridBagConstraints5 = new java.awt.GridBagConstraints ();
      gridBagConstraints5.gridheight = 2;
      gridBagConstraints5.insets = new java.awt.Insets (0, 0, 0, 4);
      jPanelBuscar.add (jButtonBuscar, gridBagConstraints5);
  
      jListBusqueda.setPreferredSize (new java.awt.Dimension(150, 100));
      jListBusqueda.setBorder (new javax.swing.border.BevelBorder(1));
      jListBusqueda.setMaximumSize (new java.awt.Dimension(150, 100));
      jListBusqueda.setMinimumSize (new java.awt.Dimension(150, 100));
  
      gridBagConstraints5 = new java.awt.GridBagConstraints ();
      gridBagConstraints5.gridx = 0;
      gridBagConstraints5.gridy = 2;
      gridBagConstraints5.gridwidth = 3;
      gridBagConstraints5.fill = java.awt.GridBagConstraints.HORIZONTAL;
      gridBagConstraints5.insets = new java.awt.Insets (5, 5, 5, 5);
      jPanelBuscar.add (jListBusqueda, gridBagConstraints5);
  

    gridBagConstraints1 = new java.awt.GridBagConstraints ();
    gridBagConstraints1.gridx = 1;
    gridBagConstraints1.gridy = 1;
    add (jPanelBuscar, gridBagConstraints1);

    jPanelConfiguracion.setLayout (new java.awt.GridBagLayout ());
    java.awt.GridBagConstraints gridBagConstraints6;
    jPanelConfiguracion.setBorder (new javax.swing.border.TitledBorder("Configuración"));

      jLabel8.setText ("Nombre");
  
      gridBagConstraints6 = new java.awt.GridBagConstraints ();
      jPanelConfiguracion.add (jLabel8, gridBagConstraints6);
  
      jTextFieldNombreConfiguracion.setPreferredSize (new java.awt.Dimension(150, 20));
      jTextFieldNombreConfiguracion.setMaximumSize (new java.awt.Dimension(150, 20));
      jTextFieldNombreConfiguracion.setMinimumSize (new java.awt.Dimension(150, 20));
  
      gridBagConstraints6 = new java.awt.GridBagConstraints ();
      gridBagConstraints6.insets = new java.awt.Insets (0, 4, 0, 4);
      jPanelConfiguracion.add (jTextFieldNombreConfiguracion, gridBagConstraints6);
  
      jButtonConfiguracion.setText ("Configuración");
      jButtonConfiguracion.addActionListener (new java.awt.event.ActionListener () {
        public void actionPerformed (java.awt.event.ActionEvent evt) {
          jButtonConfiguracionActionPerformed (evt);
        }
      }
      );
  
      gridBagConstraints6 = new java.awt.GridBagConstraints ();
      gridBagConstraints6.insets = new java.awt.Insets (4, 0, 4, 4);
      jPanelConfiguracion.add (jButtonConfiguracion, gridBagConstraints6);
  
      jLabelResultadoConfiguracion.setBorder (new javax.swing.border.EtchedBorder());
  
      gridBagConstraints6 = new java.awt.GridBagConstraints ();
      gridBagConstraints6.gridx = 0;
      gridBagConstraints6.gridy = 1;
      gridBagConstraints6.gridwidth = 3;
      gridBagConstraints6.fill = java.awt.GridBagConstraints.BOTH;
      gridBagConstraints6.insets = new java.awt.Insets (4, 4, 4, 4);
      jPanelConfiguracion.add (jLabelResultadoConfiguracion, gridBagConstraints6);
  

    gridBagConstraints1 = new java.awt.GridBagConstraints ();
    gridBagConstraints1.gridx = 0;
    gridBagConstraints1.gridy = 2;
    gridBagConstraints1.fill = java.awt.GridBagConstraints.VERTICAL;
    add (jPanelConfiguracion, gridBagConstraints1);

    jPanelActualizar.setLayout (new java.awt.GridBagLayout ());
    java.awt.GridBagConstraints gridBagConstraints7;
    jPanelActualizar.setBorder (new javax.swing.border.TitledBorder("Actualizar"));

      jLabel9.setText ("Nombre");
  
      gridBagConstraints7 = new java.awt.GridBagConstraints ();
      jPanelActualizar.add (jLabel9, gridBagConstraints7);
  
      jTextFieldNombreActualizar.setPreferredSize (new java.awt.Dimension(150, 20));
      jTextFieldNombreActualizar.setMaximumSize (new java.awt.Dimension(150, 20));
      jTextFieldNombreActualizar.setMinimumSize (new java.awt.Dimension(150, 20));
  
      gridBagConstraints7 = new java.awt.GridBagConstraints ();
      gridBagConstraints7.insets = new java.awt.Insets (2, 2, 2, 2);
      jPanelActualizar.add (jTextFieldNombreActualizar, gridBagConstraints7);
  
      jLabel10.setText ("Clave");
  
      gridBagConstraints7 = new java.awt.GridBagConstraints ();
      gridBagConstraints7.gridx = 0;
      gridBagConstraints7.gridy = 1;
      jPanelActualizar.add (jLabel10, gridBagConstraints7);
  
      jTextFieldClaveActualizar.setPreferredSize (new java.awt.Dimension(150, 20));
      jTextFieldClaveActualizar.setMaximumSize (new java.awt.Dimension(150, 20));
      jTextFieldClaveActualizar.setMinimumSize (new java.awt.Dimension(150, 20));
  
      gridBagConstraints7 = new java.awt.GridBagConstraints ();
      gridBagConstraints7.gridx = 1;
      gridBagConstraints7.gridy = 1;
      gridBagConstraints7.insets = new java.awt.Insets (2, 2, 2, 2);
      jPanelActualizar.add (jTextFieldClaveActualizar, gridBagConstraints7);
  
      jLabel11.setText ("Posición");
  
      gridBagConstraints7 = new java.awt.GridBagConstraints ();
      gridBagConstraints7.gridx = 0;
      gridBagConstraints7.gridy = 2;
      jPanelActualizar.add (jLabel11, gridBagConstraints7);
  
      jTextFieldPosicionActualizar.setPreferredSize (new java.awt.Dimension(150, 20));
      jTextFieldPosicionActualizar.setMaximumSize (new java.awt.Dimension(150, 20));
      jTextFieldPosicionActualizar.setMinimumSize (new java.awt.Dimension(150, 20));
  
      gridBagConstraints7 = new java.awt.GridBagConstraints ();
      gridBagConstraints7.gridx = 1;
      gridBagConstraints7.gridy = 2;
      gridBagConstraints7.insets = new java.awt.Insets (2, 2, 2, 2);
      jPanelActualizar.add (jTextFieldPosicionActualizar, gridBagConstraints7);
  
      jLabel12.setText ("Valor");
  
      gridBagConstraints7 = new java.awt.GridBagConstraints ();
      gridBagConstraints7.gridx = 0;
      gridBagConstraints7.gridy = 3;
      jPanelActualizar.add (jLabel12, gridBagConstraints7);
  
      jTextFieldValorActualizar.setPreferredSize (new java.awt.Dimension(150, 20));
      jTextFieldValorActualizar.setMaximumSize (new java.awt.Dimension(150, 20));
      jTextFieldValorActualizar.setMinimumSize (new java.awt.Dimension(150, 20));
  
      gridBagConstraints7 = new java.awt.GridBagConstraints ();
      gridBagConstraints7.gridx = 1;
      gridBagConstraints7.gridy = 3;
      gridBagConstraints7.insets = new java.awt.Insets (2, 2, 2, 2);
      jPanelActualizar.add (jTextFieldValorActualizar, gridBagConstraints7);
  
      jButtonActualizar.setText ("Actualizar");
      jButtonActualizar.addActionListener (new java.awt.event.ActionListener () {
        public void actionPerformed (java.awt.event.ActionEvent evt) {
          jButtonActualizarActionPerformed (evt);
        }
      }
      );
  
      gridBagConstraints7 = new java.awt.GridBagConstraints ();
      gridBagConstraints7.gridx = 0;
      gridBagConstraints7.gridy = 4;
      gridBagConstraints7.gridwidth = 2;
      gridBagConstraints7.fill = java.awt.GridBagConstraints.HORIZONTAL;
      gridBagConstraints7.insets = new java.awt.Insets (3, 3, 3, 3);
      jPanelActualizar.add (jButtonActualizar, gridBagConstraints7);
  

    gridBagConstraints1 = new java.awt.GridBagConstraints ();
    gridBagConstraints1.gridx = 1;
    gridBagConstraints1.gridy = 2;
    gridBagConstraints1.fill = java.awt.GridBagConstraints.HORIZONTAL;
    add (jPanelActualizar, gridBagConstraints1);

  }//GEN-END:initComponents

  /** Boton de Actualizar */
  private void jButtonActualizarActionPerformed (java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActualizarActionPerformed
    String nombre = jTextFieldNombreActualizar.getText();
    String clave = jTextFieldClaveActualizar.getText();
    String valor = jTextFieldValorActualizar.getText();
    int posicion = 0;
    try
    {
      posicion = Integer.parseInt(jTextFieldPosicionActualizar.getText());
    }
    catch (Exception e)
    {
      posicion = -1;
    };
    
    
    boolean huboExcepcion = false;
    
    if ((nombre.length() > 0)&&(clave.length() > 0)&&(valor.length()>0)&&(posicion != -1))
    {
      try
      {
        _contenedor._objetoRemoto.actualizar(nombre,clave,posicion,valor);
      }
      catch(Exception e)
      {
        huboExcepcion = true;
      }
      
      if (huboExcepcion == false)
      {
        JOptionPane.showMessageDialog(null,new String("Método de Actualizar ejecutado remotamente con éxito."),"TuplaAdmin :: Información",JOptionPane.INFORMATION_MESSAGE);
        jTextFieldNombreActualizar.setText("");
        jTextFieldClaveActualizar.setText("");        
        jTextFieldPosicionActualizar.setText("");
        jTextFieldValorActualizar.setText("");
      }
      else
        JOptionPane.showMessageDialog(null,new String("Método de Actualizar NO EJECUTADO"),"TuplaAdmin :: Error RMI",JOptionPane.ERROR_MESSAGE);
    }
  }//GEN-LAST:event_jButtonActualizarActionPerformed

  /** Boton de Configuracion */
  private void jButtonConfiguracionActionPerformed (java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfiguracionActionPerformed
    String nombre = jTextFieldNombreConfiguracion.getText();

    boolean huboExcepcion = false;
    
    if (nombre.length() > 0)
    {
      try
      {
        jLabelResultadoConfiguracion.setText("<html><center>" + _contenedor._objetoRemoto.configuracion(nombre) + "</center></html>");
      }
      catch(Exception e)
      {
        huboExcepcion = true;
      }
      
      if (huboExcepcion == false)
      {
        JOptionPane.showMessageDialog(null,new String("Método de Configuración ejecutado remotamente con éxito."),"TuplaAdmin :: Información",JOptionPane.INFORMATION_MESSAGE);
        jTextFieldNombreConfiguracion.setText("");
      }
      else
        JOptionPane.showMessageDialog(null,new String("Método de Configuración NO EJECUTADO"),"TuplaAdmin :: Error RMI",JOptionPane.ERROR_MESSAGE);
    }
  }//GEN-LAST:event_jButtonConfiguracionActionPerformed

  /** Boton de Busqueda */
  private void jButtonBuscarActionPerformed (java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
    String nombre = jTextFieldNombreBusqueda.getText();
    String clave = jTextFieldClaveBusqueda.getText();
    
    boolean huboExcepcion = false;
    
    if ((nombre.length() > 0)&&(clave.length() > 0))
    {
      try
      {
        _contenedor._objetoRemoto.buscar(nombre,clave);
      }
      catch(Exception e)
      {
        huboExcepcion = true;
      }
      
      if (huboExcepcion == false)
      {
        JOptionPane.showMessageDialog(null,new String("Método de Buscar ejecutado remotamente con éxito."),"TuplaAdmin :: Información",JOptionPane.INFORMATION_MESSAGE);
        jTextFieldNombreBusqueda.setText("");
        jTextFieldClaveBusqueda.setText("");        
      }
      else
        JOptionPane.showMessageDialog(null,new String("Método de Buscar NO EJECUTADO"),"TuplaAdmin :: Error RMI",JOptionPane.ERROR_MESSAGE);
    }
  }//GEN-LAST:event_jButtonBuscarActionPerformed

  /** Boton de Borrar */
  private void jButtonBorrarActionPerformed (java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarActionPerformed
    String nombre = jTextFieldNombreBorrado.getText();
    String clave = jTextFieldClaveBorrado.getText();
    
    boolean huboExcepcion = false;
    
    if ((nombre.length() > 0)&&(clave.length() > 0))
    {
      try
      {
        _contenedor._objetoRemoto.borrar(nombre,clave);
      }
      catch(Exception e)
      {
        huboExcepcion = true;
      }
      
      if (huboExcepcion == false)
      {        
        jTextFieldNombreBorrado.setText("");
        jTextFieldClaveBorrado.setText("");
        JOptionPane.showMessageDialog(null,new String("Método de Borrar ejecutado remotamente con éxito."),"TuplaAdmin :: Información",JOptionPane.INFORMATION_MESSAGE);
      }
      else
        JOptionPane.showMessageDialog(null,new String("Método de Borrar NO EJECUTADO"),"TuplaAdmin :: Error RMI",JOptionPane.ERROR_MESSAGE);
    }
  }//GEN-LAST:event_jButtonBorrarActionPerformed

  /** Boton de Insertar */
  private void jButtonInsertarActionPerformed (java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsertarActionPerformed
    String nombre = jTextFieldNombreInsertado.getText();
    String ti = jTextFieldTi.getText();
    
    boolean huboExcepcion = false;
    
    if ((nombre.length() > 0)&&(ti.length() > 0))
    {
      try
      {
        _contenedor._objetoRemoto.insertar(nombre,ti);
      }
      catch(Exception e)
      {
        huboExcepcion = true;
      }
      
      if (huboExcepcion == false)
      {
        JOptionPane.showMessageDialog(null,new String("Método de Insertar ejecutado remotamente con éxito."),"TuplaAdmin :: Información",JOptionPane.INFORMATION_MESSAGE);
        jTextFieldNombreInsertado.setText("");
        jTextFieldTi.setText("");
      }   
      else
        JOptionPane.showMessageDialog(null,new String("Método de Insertar NO EJECUTADO"),"TuplaAdmin :: Error RMI",JOptionPane.ERROR_MESSAGE);
    }
  }//GEN-LAST:event_jButtonInsertarActionPerformed

  /** Boton de Eliminar! */
  private void jButtonEliminarActionPerformed (java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
    String nombre = jTextFieldNombreEliminacion.getText();
    boolean huboExcepcion = false;
    
    if (nombre.length() > 0)
    {
      try
      {
        _contenedor._objetoRemoto.eliminar(nombre);
      }
      catch(Exception e)
      {
        huboExcepcion = true;
      }
      
      if (huboExcepcion == false)
      {
        JOptionPane.showMessageDialog(null,new String("Método de Eliminación ejecutado remotamente con éxito."),"TuplaAdmin :: Información",JOptionPane.INFORMATION_MESSAGE);
        jTextFieldNombreEliminacion.setText("");        
      }
      else
        JOptionPane.showMessageDialog(null,new String("Método de Eliminación NO EJECUTADO"),"TuplaAdmin :: Error RMI",JOptionPane.ERROR_MESSAGE);
    }
  }//GEN-LAST:event_jButtonEliminarActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JPanel jPanelEliminar;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JTextField jTextFieldNombreEliminacion;
  private javax.swing.JButton jButtonEliminar;
  private javax.swing.JPanel jPanelInsertar;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JTextField jTextFieldNombreInsertado;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JTextField jTextFieldTi;
  private javax.swing.JButton jButtonInsertar;
  private javax.swing.JPanel jPanelBorrar;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JTextField jTextFieldNombreBorrado;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JTextField jTextFieldClaveBorrado;
  private javax.swing.JButton jButtonBorrar;
  private javax.swing.JPanel jPanelBuscar;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JTextField jTextFieldNombreBusqueda;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JTextField jTextFieldClaveBusqueda;
  private javax.swing.JButton jButtonBuscar;
  private javax.swing.JList jListBusqueda;
  private javax.swing.JPanel jPanelConfiguracion;
  private javax.swing.JLabel jLabel8;
  private javax.swing.JTextField jTextFieldNombreConfiguracion;
  private javax.swing.JButton jButtonConfiguracion;
  private javax.swing.JLabel jLabelResultadoConfiguracion;
  private javax.swing.JPanel jPanelActualizar;
  private javax.swing.JLabel jLabel9;
  private javax.swing.JTextField jTextFieldNombreActualizar;
  private javax.swing.JLabel jLabel10;
  private javax.swing.JTextField jTextFieldClaveActualizar;
  private javax.swing.JLabel jLabel11;
  private javax.swing.JTextField jTextFieldPosicionActualizar;
  private javax.swing.JLabel jLabel12;
  private javax.swing.JTextField jTextFieldValorActualizar;
  private javax.swing.JButton jButtonActualizar;
  // End of variables declaration//GEN-END:variables

}