/*
 * TuplaAdmin.java
 *
 * Created on January 11, 2001, 4:04 PM
 */
 
package tuplas;
import java.rmi.*;
import javax.swing.*;

/** 
 *
 * @author  Valued Sony Customer
 * @version 
 */
public class TuplaAdmin extends javax.swing.JFrame {

  
  /** Una instancia del objeto remoto, se obtiene con el metodo conectar() */
  public TuplaD _objetoRemoto;

  /** Un panel para la conexion */
  public PanelConectar _panelConectar = new PanelConectar(this);
  
  /** Un panel para crear tuplas */
  public PanelCrear _panelCrear = new PanelCrear(this);

  
  /** Un panel para operaciones varias */
  public PanelComun _panelComun = new PanelComun(this);
  
  /** Un panel para el About */
  public PanelAbout _panelAbout = new PanelAbout();
  
  /** Determina si TuplaAdmin está conectado. */
  public boolean _conectado = false;
  
  /** Prueba la conexion RMI. */
  public void _probar() {
    try
    {
      System.out.println("Cliente Probando");
      _objetoRemoto.configuracion("PROBANDO CONEXION");
    }
    catch (Exception e)
    {
    };
  }
  
  /** Creates new form TuplaAdmin */
  public TuplaAdmin() {
    initComponents ();
    pack ();
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the FormEditor.
   */
  private void initComponents () {//GEN-BEGIN:initComponents
    jTabbedPaneDialogs = new javax.swing.JTabbedPane ();
    getContentPane ().setLayout (new java.awt.FlowLayout (0, 5, 5));
    setTitle ("TuplaAdmin");
    addWindowListener (new java.awt.event.WindowAdapter () {
      public void windowClosing (java.awt.event.WindowEvent evt) {
        exitForm (evt);
      }
    }
    );

    jTabbedPaneDialogs.addTab("Conexión",_panelConectar);
    jTabbedPaneDialogs.addTab("Crear Tuplas",_panelCrear);
    jTabbedPaneDialogs.addTab("Operaciones",_panelComun);
    jTabbedPaneDialogs.addTab("Acerca de",_panelAbout);
    jTabbedPaneDialogs.setDebugGraphicsOptions (javax.swing.DebugGraphics.BUFFERED_OPTION);
    jTabbedPaneDialogs.setDoubleBuffered (true);
    jTabbedPaneDialogs.addChangeListener (new javax.swing.event.ChangeListener () {
      public void stateChanged (javax.swing.event.ChangeEvent evt) {
        jTabbedPaneDialogsStateChanged (evt);
      }
    }
    );


    getContentPane ().add (jTabbedPaneDialogs);

  }//GEN-END:initComponents

  private void jTabbedPaneDialogsStateChanged (javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPaneDialogsStateChanged
  }//GEN-LAST:event_jTabbedPaneDialogsStateChanged


  /** Exit the Application */
  private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
    System.exit (0);
  }//GEN-LAST:event_exitForm

  
  /**
  * Main del Cliente.
  */
  public static void main (String args[]) {
    
    TuplaAdmin obj = new TuplaAdmin ();
    obj.show();
  }

  public void _cambiarPanel(java.awt.Component c)
  {
    jTabbedPaneDialogs.setSelectedComponent(c);
  }
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JTabbedPane jTabbedPaneDialogs;
  // End of variables declaration//GEN-END:variables


}